# This is a basic workflow that is manually triggered

name: NISTtheDocs2Death
description: Deploys Sphinx-built documentation to https://pages.nist.gov
author: Jonathan Guyer

branding:
  icon: book
  color: blue

inputs:
  docs-folder:
    description:
      The folder containing your sphinx docs.
    required: true
    default: "docs/"
  pages-branch:
    description: 
      The branch linked to your documentation server.
    default: 'nist-pages'
  pages-url:
    description:
      URL of web server for served documentation.
    default: 'https://pages.nist.gov'
  formats:
    description:
      Type(s) of output desired in addition to html ('pdf', and/or 'epub')
    required: false
    default: ''
  build-html-command:
    description:
      The command used to build your html documentation.
    required: false
    default: make html
  build-epub-command:
    description:
      The command used to build your ePUB documentation.
    required: false
    default: make epub
  build-pdf-command:
    description:
      The command used to build your PDF documentation.
    required: false
    default: make latexpdf
  pre-build-command:
    description:
      Run before the build command, you can use this to install system level
      dependencies, for example with
      "apt-get update -y && apt-get install -y perl"
    required: false
  apt-packages:
    description:
      List of APT packages to install.
    required: false
    default: ''
  pip-requirements:
    description:
      The path to the pip requirements file, relative to the root of the
      project.
    required: false
  conda-environment:
    description:
      The path to the Conda environment file, relative to the root of the
      project.
    required: false
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
        set-safe-directory: /github/workspace
    - name: Set env
      shell: bash
      # In a PR, github.ref_name can be, e.g., `12/merge`,
      # which causes downstream grief.
      run: |
        refname=${{ github.ref_name }}
        echo "SANITIZED_REF_NAME=${refname////_}" >> $GITHUB_ENV
    - name: Symlink current Actions repo
      # from https://github.com/orgs/community/discussions/41927#discussioncomment-4655948
      # @mbrancato
      working-directory: ${{ github.action_path }}
      shell: bash
      run: ln -fs $(realpath ./)  /home/runner/work/_actions/current
    - name: Build the docs
      id: ntd2d
      # from https://github.com/orgs/community/discussions/41927#discussioncomment-4605881
      # @mbrancato
      # because usnistgov/NISTtheDocs2Death/ntd2d@${{ github.action_ref }}
      # doesn't work
      uses: ./../../_actions/current/ntd2d
      with:
        docs-folder: ${{ inputs.docs-folder }}
        default-branch: ${{ github.event.repository.default_branch }}
        pages-branch: ${{ inputs.pages-branch }}
        pages-url: ${{ inputs.pages-url }}
        formats: ${{ inputs.formats }}
        build-html-command: ${{ inputs.build-html-command }}
        build-epub-command: ${{ inputs.build-epub-command }}
        build-pdf-command: ${{ inputs.build-pdf-command }}
        pre-build-command: ${{ inputs.pre-build-command }}
        apt-packages: ${{ inputs.apt-packages }}
        pip-requirements: ${{ inputs.pip-requirements }}
        conda-environment: ${{ inputs.conda-environment }}
    - name: Change ownership
      shell: bash
      run: |
        sudo chown -R runner:docker __nist-pages
      if: ${{ success() || steps.build-html.conclusion == 'success' }}
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        branch: ${{ inputs.pages-branch }}
        directory: __nist-pages
        github_token: ${{ github.token }}
      # Pull requests from forked repos don't have permissions
      # to push back to pages-branch
      # https://github.com/orgs/community/discussions/26829
      if: >-
        (
          github.event_name != 'pull_request'
          || github.event.pull_request.head.repo.full_name == github.repository
        ) && (success() || steps.build-html.conclusion == 'success')
    - uses: actions/upload-artifact@v3
      name: Upload Documentation Artifacts
      with:
        name: ${{ github.event.repository.name }}-${{ env.SANITIZED_REF_NAME }}-${{ github.sha }}
        path: |
          ${{ steps.ntd2d.outputs.borged-build-folder }}/html
      # Use always() to always run this step to publish documentation
      # artifacts even when there are failures
      if: ${{ always() }}
    - uses: actions/upload-artifact@v3
      name: Upload Documentation Artifacts
      with:
        name: ${{ github.event.repository.name }}-${{ env.SANITIZED_REF_NAME }}-${{ github.sha }}
        path: |
          ${{ steps.ntd2d.outputs.borged-build-folder }}/epub/*.epub
      # Use always() to always run this step to publish documentation
      # artifacts even when there are failures
      if: ${{ contains(inputs.formats, 'epub') && always() }}
    - uses: actions/upload-artifact@v3
      name: Upload Documentation Artifacts
      with:
        name: ${{ github.event.repository.name }}-${{ env.SANITIZED_REF_NAME }}-${{ github.sha }}
        path: |
          ${{ steps.ntd2d.outputs.borged-build-folder }}/latex/${{ github.event.repository.name }}.pdf
          ${{ steps.ntd2d.outputs.borged-build-folder }}/latex/${{ github.event.repository.name }}.log
          ${{ steps.ntd2d.outputs.borged-build-folder }}/latex/${{ github.event.repository.name }}.tex
      # Use always() to always run this step to publish documentation
      # artifacts even when there are failures
      if: ${{ contains(inputs.formats, 'pdf') && always() }}
