name: "Update Pages"
description: "Python Container to do actual work"
author: "Jonathan Guyer"
inputs:
  docs-folder:
    description:
      The folder containing your Sphinx configuration.
    required: true
    default: "docs/"
  default-branch:
    description:
      The default branch configured in GitHub.
    required: false
    default: "main"
  pages-branch:
    description: 
      The branch linked to your documentation server.
    required: false
    default: 'nist-pages'
  pages-url:
    description:
      URL of web server for served documentation.
    required: false
    default: 'https://pages.nist.gov'
  pip-requirements:
    description:
      The path to the pip requirements file, relative to the root of the
      project.
    required: false
  conda-environment:
    description:
      The path to the Conda environment file, relative to the root of the
      project.
    required: false
runs:
  using: "docker"
  image: "Dockerfile"
