name: "Build Documentation"

on: [push, pull_request, delete]

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: usnistgov/Docs4NIST@main
        with:
          docs-folder: docs/
          conda-environment: docs/environment.yml
          formats: |-
           epub
           pdf
