name: "Build Documentation"

on: [push, pull_request, delete]

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: usnistgov/Docs4NIST@hidden
        with:
          docs-folder: docs/
          formats: |-
           epub
           pdf
